### ISSUE TITLE
Skip operator installation when running tests

### ISSUE THREAD

**Issue by razvan** [stackabletech/ci#108]
# Description

The `scripts/run_tests.sh` has gained the ability to install operators needed for the integration tests it's self. This allows us to install different operator versions in PRs that address cross-cutting concerns:

```
▶ ./scripts/run_tests.sh --help
Unknown parameter : --help
  Usage:
     run_tests.sh [options]
  Options:
    --test-suite <test-suite>  Run a test suite from the test_definition.yaml file. Default is all tests.
    --test <test-name>         Run a specific test or a set of tests.
    --skip-delete              Skip resource deletion after the test run.
    --parallel <number>        Run tests in parallel. Default is to run all tests in parallel.
    --skip-release             Skip the operator installation.
```

To run the nightly tests from Jenkins use:

```
./scripts/run_tests.sh --test-suite nightly
```

# Acceptance criteria

* Jenkins doesn't install the operators anymore
* Jenkins uses the `run_tests.sh` script to install the operators and run tests.
* The Jenkins test suite UI field is passed as argument to the script.

**Comment by backstreetkiwi** [comment]
Update as discussed w/ @razvan:
We re-enable the dropdown for the operator version and pass the value to the test script (new version, written in Python)

**Comment by backstreetkiwi** [comment]
@razvan Can this ticket be closed? Thx.

**Comment by razvan** [comment]
> @razvan Can this ticket be closed? Thx.

Could you please also add `--log-level debug` to the `run-tests` command ? This way we can see in the logs what version of the operators was actually installed. Thanks

**Comment by backstreetkiwi** [comment]
> > @razvan Can this ticket be closed? Thx.
> 
> Could you please also add `--log-level debug` to the `run-tests` command ? This way we can see in the logs what version of the operators was actually installed. Thanks

Done

**Comment by razvan** [comment]
Works. Thanks.
