### ISSUE TITLE
Run multiple tests on one cluster?

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/ci#12]
Currently, we cannot run multiple (operator integration) tests on one cluster because the tests/operators "do not clean up properly" (quote from the devs).

This task should act as a reminder to keep the goal in mind. Some thoughts on the topic are gathered here:

* For this to work, the tests would have to install the operators themselves. This is an architecture discussion topic brought up by @razvan which is not yet solved due to prioritization
* Another prerequisite would be the cleanup of the product artifacts which is taken care of here: https://github.com/stackabletech/issues/issues/203
* @sbernauer brought up the idea of having a script erase all the Stackable-related stuff in-between test runs. In order to identify these components, we have to have something like this: https://github.com/stackabletech/issues/issues/188

**Comment by sbernauer** [comment]
For the record: i don't think we need https://github.com/stackabletech/issues/issues/203 or https://github.com/stackabletech/issues/issues/188 to purge *everything* from the cluster. My script just purges everything. And as we only deploy Stackable stuff in the t2 clusters (?) nothing else should be destroyed. IMHO https://github.com/stackabletech/issues/issues/188 is only really needed if things *not* from Stackable are running on the k8s

**Comment by razvan** [comment]
Issue for adding operator versions to the test dimensions, meaning the test suite installs the operators it is testing https://github.com/stackabletech/issues/issues/280

**Comment by backstreetkiwi** [comment]
renewed version of this issue in #89
