### ISSUE TITLE
Investigate failing Functional Cluster Tests

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/ci#16]
https://ci.stackable.tech/view/05%20Functional%20Cluster%20Tests/job/Functional%20Cluster%20Tests/209/ and the 3 previous tests failed.

Furthermore, the resources could not be cleaned up properly.

Question: Nobody seemed to care about the failures. Is it still necessary to run this test every week?

**Comment by backstreetkiwi** [comment]
@snocke @lfrancke What shall we do with the functional tests? If they are not of value for us anymore, I could take over this ticket to remove them from Jenkins completely.

**Comment by lfrancke** [comment]
That's for @snocke to decide I'm afraid. But yes: If they are not used and updated they should be removed.

**Comment by snocke** [comment]
@lfrancke From my point of view we can close the chapter of functional test and thus the stackable-cluster repository. We now have stackablectl and the demos. The demos serve the same purpose and by now they are more advanced.

**Comment by backstreetkiwi** [comment]
Okay, so I will remove the Job from Jenkins. I will assign this task to me then. Thanks.

**Comment by lfrancke** [comment]
And @snocke can you clean up repositories then?

**Comment by backstreetkiwi** [comment]
Jenkins jobs are deleted, I hand this ticket back to @snocke because of the repos

**Comment by backstreetkiwi** [comment]
Hi @snocke, if you tell me which repos have to be removed/archived, I'd be happy to take over this issue, thx.

**Comment by snocke** [comment]
Hi @backstreetkiwi, please archive this repo https://github.com/stackabletech/stackable-cluster Thank you!

**Comment by backstreetkiwi** [comment]
Hi @snocke, I am not allowed to do so but I would be happy if @lfrancke could please archive the repo https://github.com/stackabletech/stackable-cluster.

**Comment by lfrancke** [comment]
Done
