### ISSUE TITLE
Jenkins documentation test "main": add choice of platform

### ISSUE THREAD

**Issue by backstreetkiwi** [stackabletech/ci#50]
@fhennig requests the possibility to run the "main documentation test" (https://ci.stackable.tech/view/05%20Documentation%20Tests/job/_Main%20Documentation%20Test/) on any given platform.

**Comment by backstreetkiwi** [comment]
@fhennig Currently, this test is configured directly in Jenkins and is not generated by a CI job like (most of) the other tests. We created it as a prototype test and I never migrated it to the automatic test generation utility so far. I can do this during this week (starting march 20th), but I can't promise it to be finished by today. If you need to test it on another platform urgently, I can just hard-code another cluster-setup, please reach out.

**Comment by fhennig** [comment]
Thanks, will do!

**Comment by backstreetkiwi** [comment]
Analyzed and tested some stuff. I will do the following

- [ ] Add Job to Jenkins-Job-generator which has all the params and just lists the found tests
- [ ] testing-toolbox and testsuites.yaml: change structure to have a new top-level dict containing the operator tests
- [ ] test the generation
- [ ] add the generation of the main docs testsuite
- [ ] Test this in Jenkins w/o running the actual tests
- [ ] put everything together
- [ ] change Jenkins view/tab
